### ISSUE TITLE
Problem when echoing the count

### ISSUE THREAD

**Issue by denis-ev** [jessicalostinspace/commit-difference-action#7]
It might just be me, but I try to use the count and I cannot get the count to be shown outside of your action.
In the action I can see the count is 11, but the next function does not echo the count and the if action step is just getting skipped.

```
    - name: Get Commit Difference Count Between Two Branches
        id: cdc
        uses: jessicalostinspace/commit-difference-action@v1.0.0
        with:
          base-branch: 'master'
          secondary-branch: 'dev'
      - name: Echo count
        run: |
          echo ${{ steps.cdc.commit-difference-count }}
      - name: If action step
        if: "steps.cdc.commit-difference-count >= 10"
```
